spring.application.name=demo
server.servlet.context-path=/myapp
server.port=8400
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
management.endpoints.web.exposure.exclude=health,info
info.app.name=Demo App
info.app.description=Spring Boot Testing App
info.app.version=1.0.0
spring.security.user.name=gayle
spring.security.user.password=7679
coach.name=Mickey
team.name=Meeces