spring.application.name=demosecurity

# JDBC Properties
spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=springstudent
spring.datasource.password=springstudent

# Log JDBC SQL Statements
# DEV TESTING ONLY
logging.level.org.springframework.jdbc.core=TRACE
